<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" ignored="0" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="BDD Test Suite" duration-ms="39844" started-at="2018-11-04T14:20:26Z" finished-at="2018-11-04T14:21:05Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.TestRunner@10dba097]" name="runScenario" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Login Test" duration-ms="39844" started-at="2018-11-04T14:20:26Z" finished-at="2018-11-04T14:21:05Z">
      <class name="com.cornerstone.framework.Init">
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.cornerstone.framework.Init@401e7803]" name="initialize" is-config="true" duration-ms="1301" started-at="2018-11-04T15:20:24Z" finished-at="2018-11-04T15:20:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
      </class> <!-- com.cornerstone.framework.Init -->
      <class name="runners.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:runners.TestRunner@10dba097]" name="setUpClass" is-config="true" duration-ms="266" started-at="2018-11-04T15:20:26Z" finished-at="2018-11-04T15:20:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.TestRunner@10dba097]" name="runScenario" duration-ms="21010" started-at="2018-11-04T15:20:26Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2018-11-04T15:20:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login as Guest"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login via the homepage"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should be navigated to the homepage(src/test/resources/functionalTests/login.feature:30)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.TestRunner@10dba097]" name="runScenario" duration-ms="4630" started-at="2018-11-04T15:20:47Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2018-11-04T15:20:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login with credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login via the homepage"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.TestRunner@10dba097]" name="runScenario" duration-ms="4581" started-at="2018-11-04T15:20:52Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2018-11-04T15:20:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login with credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login via the homepage"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should not be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.TestRunner@10dba097]" name="runScenario" duration-ms="4809" started-at="2018-11-04T15:20:56Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2018-11-04T15:21:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login with credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login via the homepage"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should not be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.TestRunner@10dba097]" name="runScenario" duration-ms="4128" started-at="2018-11-04T15:21:01Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2018-11-04T15:21:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Login with credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login via the homepage"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:568)at org.testng.Assert.assertEquals(Assert.java:578)at stepDefinitions.LoginSteps.user_maybe_be_navigated_to_the_homepage(LoginSteps.java:68)at ✽.user should not be navigated to the homepage(src/test/resources/functionalTests/login.feature:37)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:runners.TestRunner@10dba097]" name="tearDownClass" is-config="true" duration-ms="294" started-at="2018-11-04T15:21:05Z" finished-at="2018-11-04T15:21:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runners.TestRunner -->
      <class name="com.cornerstone.framework.TearDown">
        <test-method status="PASS" signature="tear()[pri:0, instance:com.cornerstone.framework.TearDown@43a0cee9]" name="tear" is-config="true" duration-ms="558" started-at="2018-11-04T15:21:06Z" finished-at="2018-11-04T15:21:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tear -->
      </class> <!-- com.cornerstone.framework.TearDown -->
    </test> <!-- Login Test -->
  </suite> <!-- BDD Test Suite -->
</testng-results>
